server:
  port: 7060
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: http://devops-git.gsafc.com/microservices/config-center-sit.git
          search-paths: /msa
          username: sys.configurator
          password: 12345678
          
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
      
